---
- name: DevOps POC
  hosts: virtualmachines
  become: true

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: latest

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: true

    - name: Copy build files to Nginx web root
      copy:
        src: /var/lib/jenkins/workspace/ansible-pipeline
        dest: /var/www/html
        owner: nginx
        group: nginx
        mode: "0644"

    - name: Restart Nginx
      become: true
      service:
        name: nginx
        state: restarted








    

  
